### ISSUE TITLE
您好，我想请教一个问题

### ISSUE THREAD

**Issue by zhaopher** [Dream-Acc/License_Plate_Dynamic_Recognition#2]
我想要问的就是就是车牌识别系统中的其硬件部分：触发设备、摄像设备、照明设备、图像采集设备、识别车牌号码的处理机，这些硬件部分是如何组合搭配的呢，如何通过软件设计部分来进行采集识别判断

**Comment by YanhaoLi-Cc** [comment]
hi，坦率地说，这段代码是三年前编写的。
我们的项目并未使用任何硬件设备，也没有构建完整的硬件系统。所用图片均来自开源数据集，经过处理后用于实验。
识别流程相对简单：输入图片后，直接输出识别车牌号。
更多技术细节，您可以参考代码部分。

**Comment by zhaopher** [comment]
好的明白了，谢谢🙏
